services:
  postgres:
    image: postgres:16-alpine
    container_name: nebulastack-db
    environment:
      POSTGRES_DB: nebulastack
      POSTGRES_USER: nebula
      POSTGRES_PASSWORD: secretpass
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - nebula-net
    # DO NOT expose DB publicly in prod
    # ports:
    #   - "5432:5432"

  api:
    image: ghcr.io/mshahwaiz-ali/nebulastack-api:latest
    container_name: nebulastack-api
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      APP_ENV: production
      DB_HOST: postgres
      DB_NAME: nebulastack
      DB_USER: nebula
      DB_PASS: secretpass
    restart: unless-stopped
    networks:
      - nebula-net

  web:
    image: ghcr.io/mshahwaiz-ali/nebulastack-web:latest
    container_name: nebulastack-web
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - nebula-net

volumes:
  db-data:

networks:
  nebula-net:
    driver: bridge
