name: NebulaStack CI


on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  api-ci:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghr.io
      IMAGE_NAME: ghcr.io/mshahwaiz-alix/nebulastack-api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
    
      - name: Install Deps (api)
        run: |
          cd api
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Basic syntax check
        run: |
          cd api
          python -m compileall .

      - name: Build API Docker image
        run: |
          docker build -t nebulastack-api-text ./api
      
      - name: Run API tests
        run: |
          cd api
          pytest
      
      - name: Login to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push API image to GHCR
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} ./api
          docker push $IMAGE_NAME:${{ github.sha }}
  
  deploy:
    needs: api-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > /.ssh/ec2_key
          chmod 600 /.ssh/ec2_key

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            'cd Nebula-Stack-CI-CD && git pull && docker compose up -d --build'
